spring:
  application:
    name: medsol-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/swarup-bhol/medsol-config.git
server:
  port: 8888



#Configuring eureka
# eureka.client.service-url.default-zone: http://localhost:8761
  
